services:
  codesetarena-student:
    image: codesetarena-student:v7.1.9
    ports:
      - "${CODESETARENA_STUDENT_PORT:-8000}:8000"
    volumes:
      - ./data:/data
    environment:
      CODESETARENA_STUDENT_DATA_DIR: /data
